### PR TITLE
fix: ensure /tmp exists to have a consistent dir structure

### LINKED ISSUE #805: Fatal error when starting workspace
**What happened?**  
Starting a new workspace fails with a fatal error

**What did you expect to happen instead?**  
Workspace should start

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "image":"mcr.microsoft.com/devcontainers/go",
    "features": {
		"ghcr.io/devcontainers/features/node:1":{}
	},
    "customizations": {
		"vscode": {
			"settings": {},
			"extensions": [
				"streetsidesoftware.code-spell-checker",
                "mitchdenny.ecdc",
                "GitHub.copilot",
                "GitHub.copilot-chat",
                "golang.go",
                "bradlc.vscode-tailwindcss",
                "lightyen.tailwindcss-intellisense-twin",
                "Postman.postman-for-vscode"
			]
		}
	},
    "forwardPorts": [8080],
}
```

**Local Environment:**  
- DevPod Version: 0.4.2
- Operating System: mac
- ARCH of the OS: ARM64 

**DevPod Provider:**  
- Cloud Provider: onprem
- Kubernetes Provider: v1.28.2
- Local/remote provider: ssh
- Custom provider: n/a

**Anything else we need to know?**  

**Logs**
```
[13:26:33] debug SSH client created
[13:26:33] debug SSH session created
[13:26:34] info Exit error: start agent: stat /tmp: no such file or directory
[13:26:34] debug Connection to SSH Server closed
[13:26:34] info start agent: stat /tmp: no such file or directory
[13:26:34] debug Done setting up container
[13:26:34] info Process exited with status 1
[13:26:34] info run agent command
[13:26:34] info github.com/loft-sh/devpod/pkg/devcontainer/sshtunnel.ExecuteCommand.func2
[13:26:34] info /Users/runner/work/devpod/devpod/pkg/devcontainer/sshtunnel/sshtunnel.go:111
[13:26:34] info runtime.goexit
[13:26:34] info /Users/runner/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_arm64.s:1172
[13:26:34] info devcontainer up
[13:26:34] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
[13:26:34] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:95
[13:26:34] info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
[13:26:34] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:52
[13:26:34] info github.com/spf13/cobra.(*Command).execute
[13:26:34] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
[13:26:34] info github.com/spf13/cobra.(*Command).ExecuteC
[13:26:34] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
[13:26:34] info github.com/spf13/cobra.(*Command).Execute
[13:26:34] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
[13:26:34] info github.com/loft-sh/devpod/cmd.Execute
[13:26:34] info /Users/runner/work/devpod/devpod/cmd/root.go:90
[13:26:34] info main.main
[13:26:34] info /Users/runner/work/devpod/devpod/main.go:8
[13:26:34] info runtime.main
[13:26:34] info /Users/runner/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:250
[13:26:34] info runtime.goexit
[13:26:34] info /Users/runner/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_arm64.s:1172
[13:26:34] debug Connection to SSH Server closed
[13:26:34] debug Done creating devcontainer
[13:26:34] debug Done executing ssh server helper command
[13:26:34] fatal Process exited with status 1
run agent command
github.com/loft-sh/devpod/pkg/devcontainer/sshtunnel.ExecuteCommand.func2
        /Users/runner/work/devpod/devpod/pkg/devcontainer/sshtunnel/sshtunnel.go:111
runtime.goexit
        /Users/runner/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_arm64.s:1172
```

### PR DESCRIPTION
**Pull request by 89luca89**
Ensure /tmp exists, this will fix issues for creating tmpfiles and tmpdirs in container environments

Fix #805 
Resolves ENG-2398

### CODE REVIEW

File: pkg/ssh/server/ssh.go [hunk 1]
```diff
@@ -173,6 +173,12 @@ func (s *Server) handler(sess ssh.Session) {
 	ptyReq, winCh, isPty := sess.Pty()
 	cmd := s.getCommand(sess, isPty)
 	if ssh.AgentRequested(sess) {
+		// on some systems (like containers) /tmp may not exists, this ensures
+		// that we have a compliant directory structure
+		err := os.MkdirAll("/tmp", os.ModePerm)
+		if err != nil {
+			s.exitWithError(sess, perrors.Wrap(err, "creating /tmp dir"))
```
Comment (FabianKramm) [inline pkg/ssh/server/ssh.go:180]: Add a return here

File: pkg/ssh/server/ssh.go [hunk 2]
```diff
@@ -173,6 +173,12 @@ func (s *Server) handler(sess ssh.Session) {
 	ptyReq, winCh, isPty := sess.Pty()
 	cmd := s.getCommand(sess, isPty)
 	if ssh.AgentRequested(sess) {
+		// on some systems (like containers) /tmp may not exists, this ensures
+		// that we have a compliant directory structure
+		err := os.MkdirAll("/tmp", os.ModePerm)
```
Comment (FabianKramm) [inline pkg/ssh/server/ssh.go:178]: Please use 0o777 here as os.ModePerm can cause issues on other operating systems like macos (I know this shouldn't happen but we should try to avoid it)

**Review by FabianKramm — CHANGES_REQUESTED** [review]

File: pkg/ssh/server/ssh.go (hunk 1 above)
Comment (89luca89) [reply pkg/ssh/server/ssh.go:180]: done

File: pkg/ssh/server/ssh.go (hunk 2 above)
Comment (89luca89) [reply pkg/ssh/server/ssh.go]: done

**Review by FabianKramm — APPROVED** [review]

**Comment by mikecarr** [comment]
I am still seeing this on both version MacOS M1 Gui and Kubernetes Provider, am I doing something wrong?
image

And I cloned the source and ran: 
```
./hack/rebuild.sh
```
commit c9a081aab9ac76f0a59c98f335dcafefb95ae6f1 (HEAD -> main, origin/main, origin/HEAD)


[devpod-log.log](https://github.com/loft-sh/devpod/files/13461721/devpod-log.log)

**Comment by mikecarr** [comment]
Update, vscode-try-python works, when I rub vscode-try-java tries to run on Kubernetes I looked at the pod and I see the error, in container: Devpod-init

cp: can't stat '/workspaces/.dockerless/.': No such file or directory

**Comment by crkurz** [comment]
Thank you for the above fix!
Tried with 0.5.0-10 darwin x86_64 with Rancher Desktop 1.9.1 with Kubernetes v1.27.3 (Intel Mac with MacOS 13.5.2) and it got me past /tmp dir issue, but now failing at:
```
12:03:27 debug Created logger
12:03:27 debug Received ping from agent
12:03:27 debug Start setting up container...
12:03:27 info Copy /Users/ckurz/.devpod/agent/contexts/default/workspaces/test-local/content into DevContainer /workspaces/test-local
12:03:27 info Copy /var/run/docker.sock into DevContainer /var/run/docker.sock
12:03:27 info dockerless build: rename dir: open /workspaces/.dockerless/.devpod-internal: no such file or directory
12:03:27 debug Connection to SSH Server closed
12:03:27 info Error piping stdin: write |1: file already closed
12:03:27 debug Done setting up container
12:03:27 info Process exited with status 1
```

Problem seems to be:
```
12:03:27 info dockerless build: rename dir: open /workspaces/.dockerless/.devpod-internal: no such file or directory
```

Looks similar to what @mikecarr has raised above.

**Comment by mikecarr** [comment]
Thank you!!! The java project worked for me with the v0.5.0-alpha.0 version

```
12:04:25 info Starting openvscode in background...
12:04:25 info Run 'ssh vscode-remote-try-java.devpod' to ssh into the devcontainer
12:04:25 info Starting vscode in browser mode at http://localhost:10800/?folder=/workspaces/vscode-remote-try-java
12:04:29 done Successfully opened http://localhost:10800/?folder=/workspaces/vscode-remote-try-java
12:04:29 info Successfully started vscode in browser mode. Please keep this terminal open as long as you use VSCode browser version


 ❯ ./devpod-darwin-arm64 version
v0.5.0-alpha.0%
```
