### PR TITLE
fix: docker-compose feature builds do not support multiple build cont…

### LINKED ISSUE #501: Can not pull docker.io/library/dev_containers_feature_content_source image
**What happened?**
When DevPod trying to pull `docker.io/library/dev_containers_feature_content_source:latest`, an error message shows `pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

**What did you expect to happen instead?**
Image successfully pulled.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Not sure.

My `devcontainer.json`:

```
{
    "name": "Azure AD Client",
    "dockerComposeFile": "../docker-compose.yml",
    "service": "devcontainer",
    "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
    "features": {
        "ghcr.io/devcontainers/features/java:1": {
            "installMaven": "true",
            "mavenVersion": "3.8.8"
        },
        "ghcr.io/devcontainers/features/git:1": "latest"
    }
}
```

My `docker-compose.yml`:

```
version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:0-11-bullseye
    volumes:
      - .:/workspaces
      - ~/.m2/repository:/home/vscode/.m2/repository
    command: sleep infinity
```

**Local Environment:**

* DevPod Version: v0.2.1
* Operating System: mac
* ARCH of the OS: ARM64

**DevPod Provider:**

* Local/remote provider: docker

**Anything else we need to know?**
Then whole debug log:

```
[22:04:19] debug Acquire workspace lock...
[22:04:19] debug Acquired workspace lock...
[22:04:19] info Creating devcontainer...
[22:04:19] debug Inject and run command: '/Applications/DevPod.app/Contents/MacOS/devpod-cli' agent workspace up --workspace-info 'H4sIAAAAAAAA/7SSQW8aPxDFv8ucvZjlTxTFN0TyV1CbgpKlVXuJBnsIDsZeebybqGi/e+UsoFaFY4+W541/7z3v4S3ELdeoCdQerAEF+LOJVKAptLPkU/GKLYKA5uJlYWiNjUtFeWNWV8V4fF1egYB1cIYiKJBLpshyHdFv5cBQWwcjdfCJ3hPLg1ieQFheIKhjaO3Hyj143BEoMEFvKYKAUCcbPOer2/n0093j82JS3edji675Y7Rhiot+lQGVYkOdgNmXybSafZ1V35+r2cPdfFll7ZnRrhOwQ72xPifWCbCGfgOyPpFz9hU6ARya2Ofqgkb3/9k8vh1tn3fdCdCRMJur7I444a4GBaPh6L9ieF2UZVWO1XCsypsfIMAhpyVn1ksTh9hzHn3u+QV8IZ9OnKAgO82BY9pk3kldO6s/IFjeUrsIZoB1Lad5mU8sH1DPn2TfbMYHASa8eRfQLB8/g4JNSjUrKV9s2jSrgQ476cI6Fbw5qGQkR8jE8iiU7XAwGpQggN5J91lvmxVFT4m4Px86Vfsj6qlk6zmhy17W6Jgg1/b3H7mfP13qWfzzf/QLAAD//wEAAP//vdcdJHwDAAA=' --debug
[22:04:19] debug Execute command locally
[22:04:19] info Use /Users/frank/.devpod/agent/contexts/default/workspaces/azure-ad-client-java as workspace dir
[22:04:19] debug Created logger
[22:04:19] debug Received ping from agent
[22:04:19] debug Workspace Folder already exists
[22:04:19] debug Using docker command 'docker'
[22:04:19] debug Loading docker compose project [/Users/frank/Workspace/azure-ad-client-java/docker-compose.yml]
[22:04:19] debug Loaded project azure-ad-client-java-default-19db5-44715
[22:04:19] debug Process OCI feature
[22:04:19] debug Process OCI feature
[22:04:20] info #1 [devcontainer internal] load .dockerignore
[22:04:20] info #1 transferring context: 2B done
[22:04:20] info #1 DONE 0.0s
[22:04:20] info #2 [devcontainer internal] load build definition from Dockerfile-with-features
[22:04:20] info #2 transferring dockerfile: 1.33kB done
[22:04:20] info #2 DONE 0.0s
[22:04:20] info #3 [devcontainer] resolve image config for docker.io/docker/dockerfile:1.4
[22:05:10] info #3 DONE 50.1s
[22:05:10] info #4 [devcontainer] docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc
[22:05:10] info #4 CACHED
[22:05:10] info #5 [devcontainer internal] load metadata for mcr.microsoft.com/devcontainers/java:0-11-bullseye
[22:05:10] info #5 DONE 0.0s
[22:05:10] info #6 [devcontainer internal] load metadata for docker.io/library/dev_containers_feature_content_source:latest
[22:05:28] info #6 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
[22:05:28] info ------
[22:05:28] info > [devcontainer internal] load metadata for docker.io/library/dev_containers_feature_content_source:latest:
[22:05:28] info ------
[22:05:28] info failed to solve: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
[22:05:28] info exit status 17
[22:05:28] info build and extend docker-compose
[22:05:28] info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).startContainer
[22:05:28] info /Users/runner/work/devpod/devpod/pkg/devcontainer/compose.go:245
[22:05:28] info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runDockerCompose
[22:05:28] info /Users/runner/work/devpod/devpod/pkg/devcontainer/compose.go:101
[22:05:28] info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up
[22:05:28] info /Users/runner/work/devpod/devpod/pkg/devcontainer/run.go:135
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:373
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:167
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:101
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:61
[22:05:28] info github.com/spf13/cobra.(*Command).execute
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
[22:05:28] info github.com/spf13/cobra.(*Command).ExecuteC
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
[22:05:28] info github.com/spf13/cobra.(*Command).Execute
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
[22:05:28] info github.com/loft-sh/devpod/cmd.Execute
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/root.go:89
[22:05:28] info main.main
[22:05:28] info /Users/runner/work/devpod/devpod/main.go:8
[22:05:28] info runtime.main
[22:05:28] info /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
[22:05:28] info runtime.goexit
[22:05:28] info /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_arm64.s:1172
[22:05:28] info start container
[22:05:28] info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).runDockerCompose
[22:05:28] info /Users/runner/work/devpod/devpod/pkg/devcontainer/compose.go:103
[22:05:28] info github.com/loft-sh/devpod/pkg/devcontainer.(*Runner).Up
[22:05:28] info /Users/runner/work/devpod/devpod/pkg/devcontainer/run.go:135
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).devPodUp
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:373
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).up
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:167
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:101
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:61
[22:05:28] info github.com/spf13/cobra.(*Command).execute
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
[22:05:28] info github.com/spf13/cobra.(*Command).ExecuteC
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
[22:05:28] info github.com/spf13/cobra.(*Command).Execute
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
[22:05:28] info github.com/loft-sh/devpod/cmd.Execute
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/root.go:89
[22:05:28] info main.main
[22:05:28] info /Users/runner/work/devpod/devpod/main.go:8
[22:05:28] info runtime.main
[22:05:28] info /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
[22:05:28] info runtime.goexit
[22:05:28] info /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_arm64.s:1172
[22:05:28] info devcontainer up
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.(*UpCmd).Run
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:103
[22:05:28] info github.com/loft-sh/devpod/cmd/agent/workspace.NewUpCmd.func1
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/agent/workspace/up.go:61
[22:05:28] info github.com/spf13/cobra.(*Command).execute
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:916
[22:05:28] info github.com/spf13/cobra.(*Command).ExecuteC
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:1044
[22:05:28] info github.com/spf13/cobra.(*Command).Execute
[22:05:28] info /Users/runner/work/devpod/devpod/vendor/github.com/spf13/cobra/command.go:968
[22:05:28] info github.com/loft-sh/devpod/cmd.Execute
[22:05:28] info /Users/runner/work/devpod/devpod/cmd/root.go:89
[22:05:28] info main.main
[22:05:28] info /Users/runner/work/devpod/devpod/main.go:8
[22:05:28] info runtime.main
[22:05:28] info /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/proc.go:250
[22:05:28] info runtime.goexit
[22:05:28] info /Users/runner/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_arm64.s:1172
[22:05:28] debug Done executing up command
[22:05:28] debug Done creating devcontainer
[22:05:29] fatal executing agent command: exit status 1
```

### PR DESCRIPTION
**Pull request by lizardruss**
…exts

Fixes ENG-1723
Fixes #501

### CODE REVIEW

File: pkg/devcontainer/compose.go [hunk 1]
```diff
@@ -435,6 +445,55 @@ func (r *Runner) buildAndExtendDockerCompose(parsedConfig *config.SubstitutedCon
 	return buildImageName, dockerComposeFilePath, imageMetadata, extendImageBuildInfo.MetadataLabel, nil
 }
 
+func (r *Runner) buildFeatureContentImage(ctx context.Context, featureBuildInfo *feature.BuildInfo) (string, error) {
+	helper, err := r.Driver.ComposeHelper()
+	if err != nil {
+		return "", err
+	}
+
+	tempFeatureContentImage := "dev_container_feature_content_temp"
```
Comment (pascalbreuninger) [inline pkg/devcontainer/compose.go:454]: nit: could be a constant as it's not immediately clear this will be used by `getFeatureBuildOptions`

**Review by pascalbreuninger — APPROVED** [review]
small nitpick but LGTM otherwise
